language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.7.4
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
 - coverage run --source=app manage.py test
 - python manage.py test
after_success:
  - coveralls